### ISSUE TITLE
Wonderfing 1.8.x. Seems Jellyfin 1.9.1 has changed the code, might need updated?

### ISSUE THREAD

**Issue by sbsaylors** [BobHasNoSoul/jellyfin-avatars#2] opened 2024-05-15 23:59 UTC
Looking at the instructions where it asks for `"raised btnDeleteImage hide",title:"DeleteImage"})`, this doesn't seem to be there now.  Might need a quick refresh?

**Comment by BobHasNoSoul** [comment] 2024-05-16 21:10
This does need updating I will be pushing an update at the weekend :)
basically they rewrote some of the files and changed a lot of file names
/strings within the names however I will fix this as soon as I can get free
time away from work (so Saturday earliest or Sunday latest UK time)

**Comment by sbsaylors** [comment] 2024-05-16 21:12
You rock! If you have a patreon or some place to send you a few pounds/bucks. Let me know! 


The greatest obstacle to discovery is not ignorance - it is the illusion of knowledge. - Daniel J. Boorstin 

    On Thursday, May 16, 2024 at 05:10:35 PM EDT, BobHasNoSoul ***@***.***> wrote:  
 
 

This does need updating I will be pushing an update at the weekend :)
basically they rewrote some of the files and changed a lot of file names
/strings within the names however I will fix this as soon as I can get free
time away from work (so Saturday earliest or Sunday latest UK time)

**Comment by BobHasNoSoul** [comment] 2024-05-17 18:56
i got spare time early, it is now updated and confirmed working, the code was changed to jsx and seems to be working on my install let me know how you get on with it so i can close the issue :)

thanks for the offer but i dont do this to make money simply to help others enjoy the things that run on their hardware using their power using their media how they like. to me this is true freedom with open source. plus it helps others learn how things go together and to never be scared to modify things. 

and as always make a backup of anything you edit incase you accidentally hit the wrong key or something and break it (not that you would) this has been tested by me personally and confirmed as working on 10.9.0 and a friend also confirmed it when they updated to 10.9.1 so you should have no issues. but if you do you know where i am.

**Comment by micasa96** [comment] 2024-07-30 18:08
Hello, I have tried to apply the avatars section in my jellyfin 10.9.0 but I get an error, I reset in case it was a key error returning to the previous state without problem, but when I paste the code that you leave in your repository again, the message that I share with you appears again.

![image](https://github.com/user-attachments/assets/314884be-9720-42b9-bf42-f58d84a068dc)

**Comment by BobHasNoSoul** [comment] 2024-07-30 18:36
That's a minified react error saying inside one of the files, it has a typo
or a space or punctuation that should not be there, can you send me the
full content of the file you have edited?

Minifiedjs requires very specific layouts to be followed

**Comment by Netfreak25** [comment] 2024-08-18 10:22
I had the same issue like @micasa96 , noticed today that the button was gone, so i readded it according to the manual and it failed. I noticed that there were minor changes so i gave it a try -> worked!

`(0,a.jsx)(u.A,{type:"button",id:"btnDeleteImage",className:"raised hide",title:"DeleteImage"})`
had to be changed to
`(0,a.jsx)(g.A,{type:"button",id:"btnDeleteImage",className:"raised hide",title:"DeleteImage"})`
to make it work. Everything else is okay.

Server-Version 10.9.9
Web-Version 10.9.9
Build-Version 10.9.9

Linux *** 5.15.0-118-generic #128-Ubuntu SMP Fri Jul 5 09:28:59 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy

**Comment by BobHasNoSoul** [comment] 2024-08-18 20:24
Thank you for this I will update this when I get a chance and include it in
the main 10.9 page

**Closed as completed** 2024-10-24 16:39 UTC
